# Generated by Django 3.2 on 2022-08-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_favorites'),
        ('product', '0004_like'),
    ]

    operations = [
    ]
